config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'products#index'
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items 
  
  def balance
    cart_items.inject(0) {|total, item| total += (item.product.price * item.qty) }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
  
  validates :qty, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :cart_item, dependent: :destroy
  
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 1, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_cart
  
  private
  
  def current_cart
    if session[:cart_id]
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
    end
    cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
    @cart_item = CartItem.new
    @product = Product.find(params[:product_id])
  end
  
  def create
    @product = Product.find(params[:cart_item][:product_id])
    @cart_item = CartItem.new(product_id: params[:cart_item][:product_id], cart_id: params[:cart_item][:cart_id], qty: params[:cart_item][:qty])
    p params[:product_id]
    if @cart_item.save
      redirect_to root_path
    else
      render new_cart_item_path
    end
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  private
  
  def cart_item_params
    params.permit(:qty, :product_id, :cart_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
    @balance = @cart.balance
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    session[:id] = SecureRandom.uuid
    @products = Product.all.order(created_at: :DESC)
  end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      render new_product_path
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  private
  
  def product_params
    p params
    params.permit(:name, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def main
    session[:cart_id] = SecureRandom.uuid
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cart_items/new.html.erb
<%= form_for @cart_item, url: { action: :create } do |f| %>
    <p> 商品名: <%= @product.name %> </p>
    <p> 価格: <%= @product.price %> </p>
    <p>
        <%= f.label :qty, '数量' %>
        <%= f.number_field :qty %>
    </p>
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.hidden_field :cart_id, value: current_cart.id %>
    <%= f.submit 'カートに追加する' %>
<% end %>

app/views/carts/show.html.erb
<h2> カート </h2>

<% @cart.cart_items.each do |cart_item| %>
    <div>
        <%= cart_item.product.name %>
        <%= cart_item.qty %>
        <%= link_to 'カートから削除', cart_item_path(cart_item.id), method: :delete %>
    </div>
<% end %>
<p> 合計金額: <%= @balance %>円 </p>
<p> <%= link_to '商品一覧に戻る', products_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2> 商品一覧 </h2>

<% @products.each do |product| %>
    <div>
        <%= product.name %>
        <%= product.price %>
        <%= link_to '削除', product_path(product.id), method: :delete %>
        <%= link_to 'カート追加', new_cart_item_path(product_id: product.id)%>
    </div>
<% end %>

<p> <%= link_to '商品を新規登録する', new_product_path %> </p>
<p> <%= link_to 'カートを見る', cart_path(session[:id]) %></p>

app/views/products/new.html.erb
<%= form_for @product, url: { action: :create } do |f| %>
    <%= label_tag :name, '商品名' %>
    <%= text_field_tag :name %>
    <%= label_tag :price, '値段' %>
    <%= text_field_tag :price %>
    <%= submit_tag '商品を登録する' %>
<% end %>